module GeoX
  # MAPQUEST_API_KEY = 'your_key_goes_here..'
  # GOOGLE_API_KEY = 'ABQIAAAAZfX35qIl0YxrtyCKDm4rkBT_XaNMgnldu1LG_6oZDb3KRWwgDxTerw8Gxj--nfESGAf-8mQEk3iS5w' # enotify.zorched.net
  # GOOGLE_API_KEY = 'ABQIAAAAZfX35qIl0YxrtyCKDm4rkBTX2XchcwgyHzp4Xo0DHRAzt2aLjhQx_UR-FMe2iLKJFvtgEsyiPbvcVQ' # 127.0.0.1
  GOOGLE_API_KEY = 'ABQIAAAAZfX35qIl0YxrtyCKDm4rkBRdqO32N92bv4hxWDUSD48d-1lH5RQqjm4pO9wVIhG11uQbyjHqjZNCEw' # nwscdc.org
  YAHOO_API_KEY = 'eVhY.VPV34E2Q0vDQTAI.tGPNvGX3eIQKKFOMIk2nSHbhO5b7HJb.PThXPxflpqTXA--'
end
